"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { createClient } from "../../../lib/supabase/client";

type Order={id:string;status:string;grand_total:number;total:number;created_at:string;recipient_first_name?:string;recipient_last_name?:string;full_address?:string};
type Payment={id:string;status:string;amount:number;receipt_path?:string|null};

export default function OrderPage(){
 const {id}=useParams<{id:string}>(); const [order,setOrder]=useState<Order|null>(null); const [payment,setPayment]=useState<Payment|null>(null); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user){location.href="/login?next="+encodeURIComponent("/orders/"+id);return;} const {data:o}=await s.from("orders").select("*").eq("id",id).single(); if(!o){setMsg("سفارش پیدا نشد.");return;} setOrder(o); const {data:p}=await s.from("payments").select("*").eq("order_id",id).maybeSingle(); setPayment(p);})()},[id]);
 async function upload(){
  if(!file||!order)return; setBusy(true);setMsg(""); try{const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user) throw new Error("AUTH"); const ext=file.name.split(".").pop()||"bin"; const path=`${user.id}/${order.id}-${crypto.randomUUID()}.${ext}`; const up=await s.storage.from("payment-receipts").upload(path,file,{upsert:false,contentType:file.type}); if(up.error) throw up.error; const {error}=await s.from("payments").upsert({order_id:order.id,amount:Number(order.grand_total??order.total),status:"pending_review",receipt_path:path},{onConflict:"order_id"}); if(error) throw error; await s.from("orders").update({status:"slip_uploaded"}).eq("id",order.id); setMsg("رسید با موفقیت ثبت شد و برای بررسی مدیر ارسال شد."); setPayment({id:"",status:"pending_review",amount:Number(order.grand_total??order.total),receipt_path:path});}catch(e){console.error(e);setMsg("آپلود رسید انجام نشد. تنظیمات پرداخت را بررسی کنید.");}finally{setBusy(false)}}
 return <main dir="rtl" className="min-h-screen bg-[#f8f7f4] p-5"><div className="mx-auto max-w-3xl"><Link href="/orders" className="text-sm text-purple-700">← سفارش‌ها</Link><section className="mt-5 rounded-[2rem] bg-white p-7 shadow-sm">{order?<><h1 className="text-2xl font-black">سفارش #{order.id.slice(0,8)}</h1><p className="mt-2 text-gray-500">وضعیت: {order.status}</p><div className="mt-5 rounded-2xl bg-gray-50 p-5"><div>مبلغ قابل پرداخت</div><div className="mt-2 text-3xl font-black">{Number(order.grand_total??order.total).toLocaleString("fa-IR")} تومان</div></div>{!payment||payment.status==="rejected"?<div className="mt-6"><h2 className="font-bold">آپلود رسید کارت‌به‌کارت</h2><input className="mt-3 block w-full rounded-xl border p-3" type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/><button disabled={!file||busy} onClick={upload} className="mt-4 rounded-xl bg-black px-5 py-3 font-bold text-white disabled:opacity-50">{busy?"در حال ارسال...":"ارسال رسید"}</button></div>:<div className="mt-6 rounded-xl bg-amber-50 p-4 text-amber-800">رسید شما در حال بررسی مدیر است.</div>}</>:<p>{msg||"در حال بارگذاری..."}</p>}{msg&&order&&<p className="mt-4 rounded-xl bg-gray-100 p-3 text-sm">{msg}</p>}</section></div></main>
}